/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ResolveResult {
  found: boolean
  path: string
}
export function resolve(sourceInput: string, file: string, tsConfigFile: string): ResolveResult
