/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ResolveResult {
  found: boolean
  path: string
}
export interface Options {
  project?: Array<string>
}
export function resolve(sourceInput: string, file: string, options: Options): ResolveResult
